# Flutter 静态代码分析配置
# 文档: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  # 启用 custom_lint 插件（用于 riverpod_lint）
  plugins:
    - custom_lint

  # 排除不需要分析的文件
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - "lib/objectbox.g.dart"
    - ".dart_tool/**"

  # 错误级别配置
  errors:
    # 将某些警告提升为错误
    missing_required_param: error
    missing_return: error
    must_be_immutable: error

    # 将某些提示降级为信息
    todo: info
    deprecated_member_use_from_same_package: info

  # 语言特性 - 对已有项目保持宽松
  language:
    strict-casts: false
    strict-raw-types: false

linter:
  rules:
    # ============================================================
    # 错误规则 - 防止运行时错误（重要）
    # ============================================================
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_void_to_null
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps

    # ============================================================
    # 样式规则 - 代码一致性（核心）
    # ============================================================
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - implementation_imports
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - null_closures
    - overridden_fields
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - use_super_parameters
    - void_checks

    # ============================================================
    # Flutter 特定规则
    # ============================================================
    - use_build_context_synchronously
    - use_key_in_widget_constructors

    # ============================================================
    # 禁用的规则 (根据项目需求)
    # ============================================================
    # 以下规则对已有项目过于严格，暂时禁用
    # - always_put_required_named_parameters_first  # 参数顺序
    # - always_specify_types  # 与 omit_local_variable_types 冲突
    # - always_use_package_imports  # 与 prefer_relative_imports 冲突
    # - avoid_annotating_with_dynamic  # 某些情况需要 dynamic
    # - avoid_catches_without_on_clauses  # 捕获所有异常有时是必要的
    # - avoid_classes_with_only_static_members  # 工具类常用模式
    # - avoid_positional_boolean_parameters  # 改动太大
    # - avoid_redundant_argument_values  # 显式参数有时更清晰
    # - cascade_invocations  # 代码风格偏好
    # - directives_ordering  # import 排序（可后续统一处理）
    # - eol_at_end_of_file  # 文件末尾换行
    # - lines_longer_than_80_chars  # 现代屏幕足够宽
    # - omit_local_variable_types  # 有时显式类型更清晰
    # - parameter_assignments  # 参数重赋值
    # - prefer_double_quotes  # 项目使用单引号
    # - prefer_expression_function_bodies  # 有时多行更清晰
    # - prefer_final_in_for_each  # for-each 变量
    # - prefer_final_locals  # 局部变量 final
    # - prefer_int_literals  # double 字面量
    # - prefer_mixin  # 不强制使用 mixin
    # - prefer_single_quotes  # 引号风格（可后续统一处理）
    # - public_member_api_docs  # 不强制所有公共 API 都有文档
    # - require_trailing_commas  # 尾逗号
    # - sort_constructors_first  # 构造函数顺序
    # - sort_pub_dependencies  # 不强制排序依赖
    # - unawaited_futures  # 未 await 的 Future
    # - unnecessary_breaks  # switch break
    # - unnecessary_lambdas  # lambda 简化
    # - unnecessary_raw_strings  # 原始字符串


