name: daily_satori
description: "Daily Satori Tours"

publish_to: 'none'


version: 2.1.8

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  flutter:
    sdk: flutter

  # 图标
  cupertino_icons: ^1.0.8

  # getx 框架
  get:
    git:
      url: https://github.com/jonataslaw/getx
      ref: master

  # 数据库
  sqflite: ^2.4.0

  # 路径
  path: ^1.9.0
  path_provider: ^2.1.4

  # 日志
  logger: ^2.4.0

  # 分享相关
  android_intent_plus: ^5.2.0
  share_plus: ^10.1.0

  # 浏览器
  flutter_inappwebview: ^6.2.0-beta.2

  # AI 调用库
  openai_dart: ^0.4.4

  # 时间处理
  intl: ^0.20.2
  get_time_ago: ^2.0.0

  # 网络处理
  dio: ^5.7.0

  # 文件选择
  file_picker: ^8.1.2

  # 权限判断
  permission_handler: ^11.3.1

  # 引入 google 字体
  google_fonts: ^6.2.1

  # 设置界面
  flutter_settings_screens: ^0.3.4

  # 获取软件包信息
  package_info_plus: ^8.1.0

  # 打开文件
  open_file: ^3.5.9

  # 堆栈信息
  stack_trace: ^1.12.0

  # 压缩文件
  flutter_archive: ^6.0.3
  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  photo_view: ^0.15.0

  # 模板表达式
  template_expressions: ^3.3.1+2

  # shelf 框架(http server服务)
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

  # web socket 框架
  web_socket_channel: ^3.0.2

  # 网络连接
  connectivity_plus: ^6.1.2

  # 分享
  # receive_sharing_intent: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码规范
  flutter_lints: ^5.0.0

  # 数据库 orm 框架
  build_runner: ^2.4.13
  objectbox_generator: any

flutter:
  # 使用 Material Design 设计
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cover.jpeg
    - assets/js/Readability.js
    - assets/js/translate.js
    - assets/js/parse_content.js
    - assets/js/page_load_event.js
    - assets/js/common.js
    - assets/css/common.css
    - assets/easylistchina+easylist.txt
    - assets/fonts/google/
    - assets/website/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
