name: daily_satori
description: "Daily Satori Tours"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # 图标
  cupertino_icons: ^1.0.8

  # getx 框架
  get:
    git:
      url: https://github.com/jonataslaw/getx
      ref: master

  # 数据库
  sqflite: ^2.4.0

  # 路径
  path: ^1.9.0

  # 日志
  logger: ^2.4.0
  android_intent_plus: ^5.1.0
  share_plus: ^10.0.2

  # 浏览器
  flutter_inappwebview: ^6.1.4
  openai_dart: ^0.4.2

  # 分享
  # receive_sharing_intent: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码规范
  flutter_lints: ^5.0.0

flutter:
  # 使用 Material Design 设计
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cover.jpeg
    - assets/js/Readability.js
    - assets/js/main.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
