name: daily_satori
description: "Daily Satori Tours"

publish_to: 'none'


version: 3.6.51

environment:
  sdk: ^3.9.2
  flutter: ^3.35.7

dependencies:
  flutter:
    sdk: flutter

  # 图标
  cupertino_icons: ^1.0.8
  # 新增图标库
  font_awesome_flutter: ^10.10.0
  feather_icons: ^1.2.0

  # JSON序列化
  json_annotation: ^4.9.0

  # getx 框架
  get: ^5.0.0-release-candidate-9.3.2

  # 数据库
  sqflite: ^2.4.0

  # 路径
  path: ^1.9.0
  path_provider: ^2.1.4

  # 日志
  logger: ^2.4.0

  # 分享相关
  android_intent_plus: ^6.0.0
  share_plus: ^12.0.0

  # 浏览器
  flutter_inappwebview: ^6.2.0-beta.2

  # AI 调用库
  openai_dart: ^0.5.2

  # 时间处理
  intl: ^0.20.2
  get_time_ago: ^2.3.1

  # 网络处理
  dio: ^5.7.0

  # 文件选择
  file_picker: ^10.3.1

  # 权限判断
  permission_handler: ^12.0.0+1

  # 引入 google 字体
  google_fonts: ^6.2.1

  # 设置界面
  flutter_settings_screens: ^0.3.4

  # 获取软件包信息
  package_info_plus: ^9.0.0

  # 打开文件
  open_file: ^3.5.9

  # 堆栈信息
  stack_trace: ^1.12.0

  # 压缩文件
  flutter_archive: ^6.0.3
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0
  photo_view: ^0.15.0

  # Markdown相关
  flutter_markdown: ^0.7.7

  # 图片选择
  image_picker: ^1.2.0

  # 模板表达式
  template_expressions: ^3.3.1+2

  # shelf 框架(http server服务)
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

  # web socket 框架
  web_socket_channel: ^3.0.2

  # 网络连接
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0

  # yaml解析
  yaml: ^3.1.3
  cached_network_image: ^3.4.1

  # 分享
  # receive_sharing_intent: ^1.8.0

  archive: ^4.0.5
  collection: ^1.19.1

# 为了解决 template_expressions 和 objectbox 的冲突
dependency_overrides:
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 集成测试
  integration_test:
    sdk: flutter

  # 代码规范
  flutter_lints: ^6.0.0

  # JSON序列化
  json_serializable: ^6.9.5

  # 代码生成
  build_runner: ^2.4.15

  # 数据库 orm 框架
  objectbox_generator: any

flutter:
  # 使用 Material Design 设计
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/cover.jpeg
    - assets/js/Readability.js
    - assets/js/translate.js
    - assets/js/parse_content.js
    - assets/js/page_load_event.js
    - assets/js/common.js
    - assets/css/common.css
    - assets/easylistchina+easylist.txt
    - assets/fonts/google/
    - assets/website/
    - assets/configs/

  # 注册应用内置字体，避免生产环境禁用 GoogleFonts 运行时拉取导致找不到字体
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/google/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/google/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/google/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/google/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/google/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/google/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/google/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/google/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/google/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/google/Lato-BlackItalic.ttf
          weight: 900
          style: italic

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  # 注意： 运行 flutter pub run build_runner build 生成项目里面的生成代码
